name: docker

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker/
          tags: hugohh/tmo-monitor:latest

      -
        name: Push
        id: docker_build
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: docker/
          push: true
          tags: hugohh/tmo-monitor:latest
